[package]
name = "kvmlinux"
version = "0.1.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3"
derive_more = "0.99"
kvm-bindings = "0.3"
kvm-ioctls = "0.5"
libc = "0.2"
signal-hook = "0.1"
